package com.neelkanth.hangman

class WordList {
    var words = ArrayList<String>()
    // init is initializing block
    init{
        words.add("Food")
        words.add("Foot")
        words.add("Fool")
        words.add("Apple")
        words.add("Orange")
        words.add("Melon")
        words.add("Leg")
        words.add("Hand")
        words.add("Head")
        words.add("Onion")
        words.add("Shiva")
        words.add("Android")
        words.add("Litchi")
        words.add("Java")
        words.add("Computer")
        words.add("Light")
        words.add("White")
        words.add("Black")
        words.add("Blue")
        words.add("Red")
        words.add("Yellow")
        words.add("Purple")
        words.add("Halwa")
        words.add("Nice")
        words.add("Good")
        words.add("Noob")
        words.add("Pro")
        words.add("Hard")
        words.add("Easy")
        words.add("Lion")
        words.add("Monkey")
        words.add("Donkey")
        words.add("Parrot")
        words.add("Ant")
        words.add("Dog")
        words.add("Cat")
        words.add("Buffalo")
        words.add("Roti")
        words.add("Chawal")
        words.add("Daal")
        words.add("Bed")
        words.add("BCA")
        words.add("DAV")
        words.add("School")
        words.add("College")
        words.add("University")
        words.add("Bharat")
        words.add("Jalandhar")
        words.add("Punjab")
    }
}